"""Blocklist of known disposable / temporary email providers."""

DISPOSABLE_DOMAINS = {
    "mailinator.com", "guerrillamail.com", "guerrillamailblock.com",
    "grr.la", "guerrillamail.info", "guerrillamail.biz", "guerrillamail.de",
    "guerrillamail.net", "guerrillamail.org", "spam4.me",
    "tempmail.com", "temp-mail.org", "temp-mail.io", "tmpmail.net",
    "throwam.com", "throwaway.email", "throwam.net",
    "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
    "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
    "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "trashmail.com", "trashmail.at", "trashmail.me", "trashmail.net",
    "trashmail.org", "trashmail.xyz", "trashmail.io",
    "fakeinbox.com", "fakeinbox.net",
    "mailnull.com", "maildrop.cc", "dispostable.com",
    "sharklasers.com", "guerrillamail.info", "grr.la", "guerrillamail.biz",
    "spam.la", "binkmail.com", "bob.email", "clrmail.com",
    "discard.email", "discardmail.com", "discardmail.de",
    "filzmail.com", "get2mail.fr", "getonemail.com", "getonemail.net",
    "hatespam.org", "herp.in", "hideme.be", "hochsitze.com",
    "humaility.com", "ieatspam.eu", "ieatspam.info",
    "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
    "junk.to", "killmail.com", "killmail.net",
    "lookugly.com", "lortemail.dk", "mailexpire.com",
    "mailin8r.com", "mailme.lv", "mailnew.com", "mailscrap.com",
    "mailshell.com", "mailsiphon.com", "mailtemp.info",
    "mailtome.de", "mailzilla.com", "mega.zik.dj", "meltmail.com",
    "momentics.ru", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "mt2009.com", "mt2014.com", "mytrashmail.com",
    "netmails.com", "netmails.net", "nospamfor.us", "nospamthanks.info",
    "notmailinator.com", "nowmymail.com", "nwldx.com",
    "objectmail.com", "obobbo.com", "oneoffemail.com", "onewaymail.com",
    "otherinbox.com", "owlpic.com",
    "pjjkp.com", "plexolan.de", "pookmail.com", "proxymail.eu",
    "prtnx.com", "rcpt.at", "rklips.com",
    "rmqkr.net", "rppkn.com", "rtrtr.com",
    "s0ny.net", "safe-mail.net", "saynotospams.com",
    "selfdestructingmail.com", "sendspamhere.com",
    "sharedmailbox.org", "shieldedmail.com", "shitmail.me",
    "skeefmail.com", "smellfear.com",
    "sneakemail.com", "snkmail.com", "sofort-mail.de",
    "sogetthis.com", "spam.la", "spamavert.com",
    "spamcorpse.com", "spamex.com", "spamgourmet.com",
    "spamgourmet.net", "spamgourmet.org", "spamherelots.com",
    "spamhereplease.com", "spamhole.com", "spamify.com",
    "spaminator.de", "spamkill.info", "spaml.com",
    "spammotel.com", "spamobox.com", "spamspot.com",
    "spamthis.co.uk", "spamthisplease.com",
    "spamtrail.com", "speed.1s.fr", "supergreatmail.com",
    "suremail.info", "sweetxxx.de",
    "tagyourself.com", "teewars.org", "teleworm.com",
    "teleworm.us", "tempalias.com", "tempe-mail.com",
    "tempemail.biz", "tempemail.com", "tempemail.net",
    "tempinbox.com", "tempinbox.co.uk",
    "tempmail.eu", "tempmail2.com", "tempr.email",
    "tempomail.fr", "temporarily.de", "temporaryemail.net",
    "temporaryemail.us", "temporaryforwarding.com",
    "temporaryinbox.com", "temporarymail.org", "tempthe.net",
    "thankyou2010.com", "thisisnotmyrealemail.com",
    "throwam.com", "tilien.com", "tittbit.in",
    "tizi.com", "tmailinator.com", "toiea.com",
    "trashdevil.com", "trashdevil.de", "trashemail.de",
    "trashimail.de", "trashmail.at", "trashmail.com",
    "trashmail.io", "trashmail.me", "trashmail.net",
    "trashmail.org", "trashmail.xyz",
    "trashmailer.com", "trashymail.com",
    "trbvm.com", "turual.com", "twinmail.de",
    "tyldd.com", "uggsrock.com", "umail.net",
    "uroid.com", "us.af", "venompen.com",
    "veryrealemail.com", "viditag.com", "viewcastmedia.com",
    "viewcastmedia.net", "viewcastmedia.org",
    "warnme.me", "webemail.me", "weg-werf-email.de",
    "wegwerf-email-addressen.de", "wegwerf-emails.de",
    "wegwerfadresse.de", "wegwerfemail.de", "wegwerfemail.net",
    "wegwerfemail.org", "wegwerfmail.de", "wegwerfmail.info",
    "wegwerfmail.net", "wegwerfmail.org", "wh4f.org",
    "whyspam.me", "willhackforfood.biz",
    "willselfdestruct.com", "wuzupmail.net",
    "xagloo.com", "xemaps.com", "xents.com", "xmaily.com",
    "xoxy.net", "xyzfree.net", "yapped.net", "yeah.net",
    "yep.it", "yogamaven.com", "yourdomain.com",
    "ypmail.webarnak.fr.eu.org", "yuurok.com", "z1p.biz",
    "za.com", "zehnminuten.de", "zehnminutenmail.de",
    "zippymail.info", "zoemail.net", "zoemail.org",
    "zomg.info", "zxcv.com", "zxcvbnm.com",
    # Common shortlived services
    "guerrillamail.com", "spam4.me", "dispostable.com",
    "getnada.com", "mailnesia.com", "spamgap.com",
    "tempail.com", "emailondeck.com", "mohmal.com",
    "spamwc.de", "brefmail.com", "inoutmail.de",
    "inoutmail.eu", "inoutmail.info", "inoutmail.net",
    "mail-temporaire.fr", "mail-temporaire.com",
    "tempr.email", "discard.email",
    "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "10minutemail.co.uk", "10minutemail.de",
    "10minutemail.ru", "10minutemail.us",
    "20minutemail.com", "30minutemail.com",
    "60minutemail.com",
    "mintemail.com", "minutemail.com",
    "spamgourmet.com",
}


def is_disposable(email: str) -> bool:
    domain = email.split("@")[-1].lower().strip()
    return domain in DISPOSABLE_DOMAINS
